name: Deploy Marketing

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deload/deload-marketing
            git pull origin main
            pnpm install
            pnpm run build
            sudo chmod -R 755 ~/deload/deload-marketing/dist
            sudo systemctl restart nginx
